### ISSUE TITLE
Link external spirv-cross repo instead of submodule?

### ISSUE THREAD

**Issue by shinchiro** [rossy/crossc#4]
Is there an easy way to link crossc with external spirv-cross? Since shaderc also required spirv-cross now, I thought of having one repo of spirv-cross only.

**Comment by Akaricchi** [comment]
There is currently no easy way, because crossc hardcodes the spirv-cross source paths in its build system. I assume it's done this way because spirv-cross does not have a proper version and does not ship a pkg-config file. You can try replacing the submodule with a symlink locally, but you might have to also fix the makefile then.

FWIW, shaderc no longer requires SPIRV-Cross by default: https://github.com/google/shaderc/commit/fdecc635e2a99c2f962898913e02d89238cc4cbb

**Comment by shinchiro** [comment]
I thought so. I already try deleting submodule and symlink with external one. It works without modifying makefile but not really feasible.

Btw, all is good now after shaderc didn't impose mandatory having spirv-cross in its build system anymore.

**Comment by rossy** [comment]
Yeah, currently crossc uses hardcoded paths into the submodule. It was done this way because technically, the crossc version is tightly coupled to the SPIRV-Cross version, since SPIRV-Cross' C++ API has no official guarantee of API stability (even though in practice, SPIRV-Cross' API is pretty stable and updating SPIRV-Cross is totally fine.)

FYI, SPIRV-Cross has its own API and ABI-stable C API now, so the best solution for this is probably to deprecate crossc and port mpv to use SPIRV-Cross directly.
